version: "3"
services:
  dbmysql:
    image: mysql/mysql-server:5.5
    restart: always 
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'mydb'
       MYSQL_USER: 'demo'
       MYSQL_PASSWORD: "password"
       MYSQL_ROOT_PASSWORD: "password"
       MYSQL_ROOT_HOST: "%"
    volumes:
      - "/data/mysql:/var/lib/mysql"
    network_mode: bridge